### ISSUE TITLE
Better error handling for roles

### ISSUE THREAD

**Issue by LuCkEr-** [Kiyomi-Parents/Kiyomi#67]
```python
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<Loop._loop() done, defined at /home/kiyomi/Kiyomi/venv/lib/python3.9/>
Traceback (most recent call last):
  File "/home/kiyomi/Kiyomi/venv/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 125, in _loop
    raise exc
  File "/home/kiyomi/Kiyomi/venv/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/kiyomi/Kiyomi/src/utils.py", line 19, in wrapper
    res = await func(self, *args, **kwargs)
  File "/home/kiyomi/Kiyomi/src/utils.py", line 35, in wrapper
    return await func(self, *args, **kwargs)
  File "/home/kiyomi/Kiyomi/src/utils.py", line 81, in wrapper
    result = await func(self, *args, **kwargs)
  File "/home/kiyomi/Kiyomi/src/cogs/achievement_roles/tasks.py", line 37, in update_member_roles
    await self.update_member_pp_roles(guild_member)
  File "/home/kiyomi/Kiyomi/src/cogs/achievement_roles/tasks.py", line 66, in update_member_pp_roles
    await self.remove_member_role(guild_member.guild_id, guild_member.member_id, remove_role_member)
  File "/home/kiyomi/Kiyomi/src/cogs/achievement_roles/tasks.py", line 86, in remove_member_role
    await general.remove_role_from_member(
  File "/home/kiyomi/Kiyomi/src/cogs/general/general_api.py", line 46, in remove_role_from_member
    await self.actions.remove_role_from_member(guild_id, member_id, role_id, reason)
  File "/home/kiyomi/Kiyomi/src/cogs/general/actions.py", line 129, in remove_role_from_member
    discord_role = await self.get_discord_role(guild_id, role_id)
  File "/home/kiyomi/Kiyomi/src/cogs/general/actions.py", line 55, in get_discord_role
    raise RoleNotFoundException(f"Could not find role with id {role_id} in guild {discord_guild.name}")
src.cogs.general.errors.RoleNotFoundException: Could not find role with id 9 in guild Smugle Stick
```

**Comment by LuCkEr-** [comment]
Fixed
